Fix serial access to GPS
The python serial module makes use of select. Unfortunately, our
application opens enough files that select can fail:

    File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 556, in write
      abort, ready, _ = select.select([self.pipe_abort_write_r], [self.fd], [], None)
    ValueError: filedescriptor out of range in select()

The GPS connection is currently over USB and the serial device
presented does not require serial semantics. Write and flush
should be sufficient.

Bugfix: VRVDR-49930